### ISSUE TITLE
The extension turns itself on after some time when it was manually turned off

### ISSUE THREAD

**Issue by adamency** [igorlogius/dont-open-duplicate-tabs#10]
I've checked it three times in a row. I turn the extension off, the icon goes "OFF" and it all goes well for 2 minutes, then after some times the extension is once again "ON" without any manual user input.
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 108.1
 - Version: last release

**Comment by igorlogius** [comment]
That is actually a feature, which i forgot to document ... 
I swear it made sense at the time :-D, since i thought that people would only briefly want to turn of the addon ... and the auto-reenable would be neat because nobody would forget to re-enable it afterwards. 

But i have to admit ... looking back ... i am not so sure that this was my best idea.

**Comment by igorlogius** [comment]
Done

**Comment by adamency** [comment]
haha, I agree. A program should respect explicit user input above all else. However, since you've already implemented that feature, you could make it as an optional feature that can be turned on/off in options. Anyway, thanks a lot for your swift answer !

**Comment by adamency** [comment]
@igorlogius You've been starred ! (I've been using your addon ever since you made this fixed ;) )
